### PR TITLE
支持Swoole的cURL handle

### PR DESCRIPTION
**Pull request by coleflowers**
支持Swoole的cURL handle，运行测试环境：

$php --version
PHP 7.4.14 (cli) (built: Mar 23 2021 11:21:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team team@swoole.com
Version => 4.6.2
Built => Mar 23 2021 16:33:39
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1j 16 Feb 2021
dtls => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

### CODE REVIEW

**Comment by sy-records** [comment]
这个不需要支持了，Swoole增加原生curl hook了

**Review by sy-records — CHANGES_REQUESTED** [review]
```php 
$curl_handle instanceof \Swoole\Curl\Handler
```

如果不安装Swoole的话，找不到这个类也会异常

高版本直接使用`SWOOLE_HOOK_NATIVE_CURL`就可以了，不需要兼容

**Comment by coleflowers** [comment]
```php
<?php

class B {

}
$curl_handle = new B();
if (class_exists('\Swoole\Curl\Handler')) {
	echo 'yes' . PHP_EOL;
} else {
	echo 'no' . PHP_EOL;
}
if (is_resource($curl_handle) || ($curl_handle instanceof \Swoole\Curl\Handler)) {
	echo 'yes' . PHP_EOL;
} else {
	echo 'no' . PHP_EOL;
}
$curl_handle = curl_init();
if (is_resource($curl_handle) || ($curl_handle instanceof \Swoole\Curl\Handler)) {
	echo 'yes' . PHP_EOL;
} else {
	echo 'no' . PHP_EOL;
}
```

```bash
$php -m | grep swoole
$php test.php 
no
no
yes
```

**Comment by coleflowers** [comment]
@sy-records 那要考虑加入加入如下判断嘛？

```php
if ($curl_handle instanceof \Swoole\Curl\Handler) {
    throw new RequestCore_Exception('Please set SWOOLE_HOOK_NATIVE_CURL');
}
```

不然会有如下奇怪的异常
```
OSS\Core\OssException: :  RequestId: 
```

**Comment by sy-records** [comment]
我不是阿里的，这里是is_resource判断的问题，等兼容php8以后就可以了 #153

**Comment by huiguangjun** [comment]
fixed in v2.6.0

**Pull request closed without merging**
